### ISSUE TITLE
casing_Simulation.mesh does not have the attribute "pad_for_casing_and_data"

### ISSUE THREAD

**Issue by Eltayieb** [simpeg-research/heagy-2021-tle-casing#2]
Hi Lindsey,

I was attempting to run the jupyter notebook, called "em_conductive_casing" that was used to produce some results in the "Electrical and electromagnetic responses over steel-cased wells" paper. However, I get the error module 'casingSimulations.mesh' has no attribute 'pad_for_casing_and_data'. What would you recommend in this case?

Thanks in advance for your attention. I am looking forward to your answer.

Kind regards,
Mahmoud Eltayieb

**Comment by lheagy** [comment]
Hi @Eltayieb, apologies for taking so long to get back to you here! In #4, I updated the environment file to point to the branches on SimPEG and casingSimulations that are needed for running the notebooks. Please give it a try when you have a chance and feel free to re-open this issue if you are still running into problems

**Comment by lacorey14** [comment]
Hi Lindsey, I have the same problem ('casingSimulations.mesh' has no attribute 'pad_for_casing_and_data') when running the notebook. I am using the Simpeg==0.14.3 and the casingSimulations=0.1.0. The comments above did not solve the problem. I have checked  the casingSimulations and did not find the pad_for_casing_and_data. Is the casingSimulations updated?
