### ISSUE TITLE
NotImplementError

### ISSUE THREAD

**Issue by Eltayieb** [simpeg-research/heagy-2021-tle-casing#3]
Hi Lindsey,

While modifying the jupyter note, called "em_conductive_casing" that was used in the "Electrical and electromagnetic responses over steel-cased wellls" paper. I got the following error:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-33-db75a207eb6f> in <module>
----> 1 fields = simulation_simpeg.fields(cond_model)

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/simulation.py in fields(self, m)
     58 
     59         # set initial fields
---> 60         f[:, self._fieldType + "Solution", 0] = self.getInitialFields()
     61 
     62         if self.verbose:

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/simulation.py in getInitialFields(self)
    390 
    391         for i, src in enumerate(Srcs):
--> 392             ifields[:, i] = ifields[:, i] + getattr(
    393                 src, "{}Initial".format(self._fieldType), None
    394             )(self)

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/sources.py in jInitial(self, prob)
    554 
    555     def jInitial(self, prob):
--> 556         raise NotImplementedError
    557 
    558     def hInitial(self, prob):

NotImplementedError:
---------------------------------------------------------------------------

Thanks in advance for your attention. I am always happy to hear from you.

Kind regards,
Mahmoud Eltayieb

**Comment by lheagy** [comment]
Thanks @Eltayieb! This should be resolved with #4. Please feel free to re-open if you are still running into issues.
