### ISSUE TITLE
NotImplementError： 

### ISSUE THREAD

**Issue by lacorey14** [simpeg-research/heagy-2021-tle-casing#5]
Hi, Hi Lindsey,
   I have checked two closed issue, as I have the same problem when running the notebook. The solution in 4# did not solve my problem. As the casingsimulations (ver = 0.1.0) are installed locally, and I have not found any updates yet, it may be the issue caused by the version of SIMPEG? Yet I have tried many versions of SIMPEG and the same issue presents.

---------------------------------------------------------------
NotImplementedError Traceback (most recent call last)
in
----> 1 fields = simulation_simpeg.fields(cond_model)

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/simulation.py in fields(self, m)
58
59 # set initial fields
---> 60 f[:, self._fieldType + "Solution", 0] = self.getInitialFields()
61
62 if self.verbose:

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/simulation.py in getInitialFields(self)
390
391 for i, src in enumerate(Srcs):
--> 392 ifields[:, i] = ifields[:, i] + getattr(
393 src, "{}Initial".format(self._fieldType), None
394 )(self)

~/.local/lib/python3.8/site-packages/SimPEG/electromagnetics/time_domain/sources.py in jInitial(self, prob)
554
555 def jInitial(self, prob):
--> 556 raise NotImplementedError
557
558 def hInitial(self, prob):

**Comment by lheagy** [comment]
Hi @lacorey14, apologies for my late reply here! I have updated the [environment file](https://github.com/simpeg-research/heagy-2021-tle-casing/blob/main/environment.yml) to specify that you will need to be running SimPEG `0.17.0` for these notebooks. Please give that a try and feel free to re-open this issue if you are still running into errors.
